# Generated by Django 5.1.6 on 2025-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('english', 'English'), ('bangla', 'Bangla')], max_length=50)),
                ('voice_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
