# Generated by Django 5.1.6 on 2025-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemodel',
            name='voice_code',
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
        migrations.AlterField(
            model_name='voicemodel',
            name='language',
            field=models.CharField(choices=[('bn', 'Bengali'), ('en', 'English')], max_length=50),
        ),
    ]
